---
- name: Install dependencies
  package:
    name: "{{ grafana_dependencies }}"
    state: present
  register: _install_dep_packages
  until: _install_dep_packages | success
  retries: 5
  delay: 2

- name: Remove conflicting grafana packages
  package:
    name: grafana-data
    state: absent
  register: old_grafana_pkgs

- name: Clean apt cache
  command: apt clean
  #  tags:
  #    - ansible_skip_lint
  when:
    - old_grafana_pkgs is changed
    - ansible_pkg_mgr == "apt"

- name: Add Grafana repository file [RHEL/CentOS]
  template:
    src: grafana.yum.repo.j2
    dest: /etc/yum.repos.d/grafana.repo
    force: yes
    backup: yes
  when: ansible_pkg_mgr == "yum"

- block:
  - name: Import Grafana GPG signing key [Debian/Ubuntu]
    apt_key:
      url: "https://packagecloud.io/gpg.key"
      state: present
      validate_certs: false
    register: _add_apt_key_x86
    until: _add_apt_key_x86 | success
    retries: 5
    delay: 2
    environment:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
    when: ansible_architecture == "x86_64"

  - name: Add Grafana repository [Debian/Ubuntu]
    apt_repository:
      repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
      state: present
      update_cache: no
    register: _apt_add_repo_x86
    when: ansible_architecture == "x86_64"

  - name: Import Grafana GPG signing key [Raspbian]
    apt_key:
      url: "https://bintray.com/user/downloadSubjectPublicKey?username=bintray"
      state: present
      validate_certs: false
    register: _add_apt_key_arm
    until: _add_apt_key_arm | success
    retries: 5
    delay: 2
    when: ansible_architecture == "armv6l" or ansible_architecture == "armv7l"

  - name: Add Grafana repository [Raspbian]
    apt_repository:
      repo: "deb {% if ansible_architecture == 'armv6l' %}https://dl.bintray.com/fg2it/deb-rpi-1b{% else %}https://dl.bintray.com/fg2it/deb{% endif %} {{ ansible_distribution_release }} main"
      state: present
      update_cache: no
    register: _apt_add_repo_arm
    when: ansible_architecture == "armv6l" or ansible_architecture == "armv7l"

  - name: Update Apt cache
    apt:
      update_cache: yes
    when:
      - ( _apt_add_repo_x86 | changed ) or
        ( _apt_add_repo_arm | changed ) or
        ( _add_apt_key_x86 | changed ) or
        ( _add_apt_key_arm | changed )
    register: _update_apt_cache
    until: _update_apt_cache | success
    retries: 5
    delay: 2
  when:
    - ansible_pkg_mgr == "apt"

- name: Install Grafana
  package:
    name: "{{ grafana_package }}"
    state: present
  register: _install_packages_present
  until: _install_packages_present | success
  retries: 5
  delay: 2
  notify: restart grafana
  when: grafana_version != "latest"

- name: Install latest Grafana version
  package:
    name: grafana
    state: latest
  register: _install_packages_latest
  until: _install_packages_latest | success
  retries: 5
  delay: 2
  when: grafana_version == "latest"
  tags:
    - skip_ansible_lint
