---
- name: Check variable types
  assert:
    that:
      - grafana_server is mapping
      - grafana_database is mapping
      - grafana_security is mapping

- name: Fail on unsupported system architectures
  fail:
    msg: "Sorry grafana doesn't support {{ ansible_architecture }} on this OS family ({{ ansible_os_family }}). Exiting."
  when:
    - ansible_architecture != "x86_64"
    - not ( ansible_architecture in ['armv6l', 'armv7l'] and ansible_os_family == 'Debian' )

- name: Fail when datasources aren't configured when dashboards are set to be installed
  fail:
    msg: "You need to specify datasources for dashboards!!!"
  when: grafana_dashboards != [] and grafana_datasources == []

- name: Fail when grafana admin password isn't set
  fail:
    msg: "Please specify grafana admin password (grafana_security.admin_password)"
  when: grafana_security.admin_password == ''

- name: Fail on incorrect variable types in datasource definitions
  fail:
    msg: "Boolean variables in grafana_datasources shouldn't be passed as strings. Please remove unneeded apostrophes."
  when: ( item.isDefault is defined and item.isDefault is string ) or
        ( item.basicAuth is defined and item.basicAuth is string )
  with_items: "{{ grafana_datasources }}"

- name: Fail on bad database configuration
  fail:
    msg: "Wrong database configuration. Please look at http://docs.grafana.org/installation/configuration/#database"
  when: ( grafana_database.type == "sqlite3" and grafana_database.url is defined ) or
        ( grafana_database.type != "sqlite3" and grafana_database.path is defined ) or
        ( grafana_database.type == "sqlite3" and grafana_database.host is defined ) or
        ( grafana_database.type == "sqlite3" and grafana_database.user is defined ) or
        ( grafana_database.type == "sqlite3" and grafana_database.password is defined ) or
        ( grafana_database.type == "sqlite3" and grafana_database.server_cert_name is defined )

- name: Fail when grafana domain isn't properly configured
  fail:
    msg: "Check server configuration. Please look at http://docs.grafana.org/installation/configuration/#server"
  when:
    - grafana_server.root_url is defined
    - grafana_server.root_url | search(grafana_server.domain)

- name: Fail when grafana_api_keys uses invalid role names
  fail:
    msg: "Check grafana_api_keys. The role can only be one of the following values: Viewer, Editor or Admin."
  when:
    - item.role not in ['Viewer', 'Editor', 'Admin']
  with_items: "{{ grafana_api_keys }}"
